### ISSUE TITLE
make run command don't work

### ISSUE THREAD

**Issue by JudikaelNedev** [kheeklab/privacyidea-docker#126] opened 2024-04-01 15:31 UTC
root@docker-it:/home/mathematic/privacyidea-docker# make run
privacyidea-dev
privacyidea-dev
mkdir /tmp/privacyidea-data
docker run -p 8080:8080 -ti --name=privacyidea-dev --env-file=secretkey --env-file=pipepper khalibre/privacyidea:dev
[PrivacyIDEA] To SSH into this container, run: "docker exec -it 848fa0958f35 /bin/bash".

/usr/local/bin/privacyidea_entrypoint.sh: line 14: [: missing `]'

             _                    _______  _______
   ___  ____(_)  _____ _______ __/  _/ _ \/ __/ _ |
  / _ \/ __/ / |/ / _ `/ __/ // // // // / _// __ |
 / .__/_/ /_/|___/\_,_/\__/\_, /___/____/___/_/ |_|
/_/                       /___/

[PrivacyIDEA] Starting . To stop the container with CTRL-C, run this container with the option "-it".

[WARNING] PI_DB_VENDOR environment variable is not set. Using default SQLite...

[privacyIDEA] The directory /mnt/privacyidea/files does not exist or is empty. Copy any files to this directory to have them copied to /opt/privacyidea before privacyIDEA starts.

[privacyIDEA] The directory /mnt/privacyidea/scripts does not exist. Copy any scripts to this directory to have them executed, in alphabetical order, before privacyIDEA starts.

[INFO] Creating keys directory...

[INFO]  Encryption key file not found, creating a new one...

/usr/local/bin/configure_privacyidea.sh: line 88:    10 Illegal instruction     (core dumped) pi-manage create_enckey
make: *** [Makefile:16: run] Error 132
root@docker-it:/home/mathematic/privacyidea-docker# ls
CODE_OF_CONDUCT.md  LICENSE   prebuildfs        rootfs
Dockerfile          Makefile  README.md         secretkey

**Comment by mr-ssd** [comment] 2024-04-02 02:15
@JudikaelNedev thank for reporting your issue. I'll check this.
anyway did you try run `make build` before `make run`?

**Comment by mr-ssd** [comment] 2024-04-02 08:24
I could not reproduce this issue not main branch. Should you give me more detail such as your OS. Docker version and branch name...?

**Comment by mr-ssd** [comment] 2024-04-23 04:35
since there is no respond I'll close this

**Closed as completed by mr-ssd** 2024-04-23 04:35 UTC
Labels: possible bug, need more info
